module.exports = {
    SESSION_ID_TAKEN: 'SESSION_ID_TAKEN',
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    SESSION_FULL: 'SESSION_FULL',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    INVALID_DECK_CODE: 'INVALID_DECK_CODE',
};
